import type { Metadata } from "next";

import "./globals.css";
import { inter } from "./fonts/fonts";
import { Provider } from "./components/ui/provider";



export const metadata: Metadata = {
  title: "CV Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} text-white`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
