import type { Metadata } from "next";

import "./globals.css";
import { inter } from "./fonts/fonts";



export const metadata: Metadata = {
  title: "CV Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} text-white`}
      >
        {children}
      </body>
    </html>
  );
}
